name: Run Tests
on: [push, pull_request]
jobs:
  drive:
    env:
      app_staging_secret: ${{secrets.app_staging_secret}}
    strategy:
      matrix:
        device:
          - "iPhone 11"
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: List all simulators
        run: "xcrun instruments -s"
      - name: Start Simulator
        run: xcrun simctl boot E766D3DF-D016-40B7-AFF4-18B566FB5BF3
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: |
          cp lib/.env.dart.example lib/.env.dart
          cp android/app/build.gradle.prod android/app/build.gradle
          sed -i -e 's/secret/${{secrets.app_staging_secret}}/g' lib/.env.dart
      - name: Run Tests
        run: flutter drive --target=test_driver/login_it.dart