name: Run Tests
on: [push, pull_request]
jobs:
  drive:
    env:
      staging_secret: ${{secrets.staging_secret}}
      staging_url: ${{secrets.staging_url}}
      firebase_ios: ${{secrets.firebase_ios}}
    strategy:
      matrix:
        device:
          - "iPhone 11"
      fail-fast: false
    runs-on: macOS-latest
    steps:
      - name: List all simulators
        run: "xcrun instruments -s"
      - name: Start Simulator
        run: xcrun simctl boot E766D3DF-D016-40B7-AFF4-18B566FB5BF3
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: |
          cp lib/.env.dart.example lib/.env.dart
          cp android/app/build.gradle.prod android/app/build.gradle
          sed -i -e 's/secret/${{secrets.staging_secret}}/g' lib/.env.dart
          sed -i -e 's/example.com/${{secrets.staging_url}}/g' lib/.env.dart
          echo ${{secrets.firebase_ios}} | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Run Tests
        run: flutter drive --target=test_driver/login_it.dart