name: Run Tests
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Run Tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 29]
        target: [default]
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: |
          cp lib/.env.dart.example lib/.env.dart
          cp android/app/build.gradle.prod android/app/build.gradle
          sed -i 's/secret/password/g' lib/.env.dart
          sed -i 's/dns/${{secrets.app_sentry}}/g' lib/.env.dart
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --target=test_driver/all_it.dart